# Generated by Django 3.2.6 on 2021-08-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('title', models.TextField()),
                ('article_author', models.TextField()),
                ('pub_date', models.DateField()),
                ('tags', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
